### ISSUE TITLE
Error At running Multi-RTL!

### ISSUE THREAD

**Issue by hakam1234** [ptrkrysik/multi-rtl#5]
i got gnuradio 3.7
i have install manual gr-osmosdr also i tried by using apt-get gr-osmosdr but it will get install like that the gnuradio 3.8 and other files 
any help ?

```
root@kali:~/multi-rtl/examples# ./mutlirtl_rx_to_cfile_2chan.py
Traceback (most recent call last):
  File "./mutlirtl_rx_to_cfile_2chan.py", line 17, in <module>
    import multi_rtl
  File "/usr/local/lib/python2.7/dist-packages/multi_rtl/__init__.py", line 30, in <module>
    from multi_rtl_source import multi_rtl_source
  File "/usr/local/lib/python2.7/dist-packages/multi_rtl/multi_rtl_source.py", line 27, in <module>
    import osmosdr
  File "/usr/local/lib/python2.7/dist-packages/osmosdr/__init__.py", line 26, in <module>
    from osmosdr_swig import *
  File "/usr/local/lib/python2.7/dist-packages/osmosdr/osmosdr_swig.py", line 13, in <module>
    from . import _osmosdr_swig
ImportError: /usr/local/lib/libgnuradio-osmosdr-0.1.5.so.0.0.0: undefined symbol: _ZN5boost6chrono12steady_clock3nowEv
```

**Comment by antoniprzybylik** [comment]
This project only works with gnuradio 3.7. However, I have ported it to gnuradio 3.8 so if you want to use this project with gnuradio 3.8 check out my fork: https://github.com/antoniprzybylik/multi-rtl

**Comment by hakam1234** [comment]
> This project only works with gnuradio 3.7. However, I have ported it to gnuradio 3.8 so if you want to use this project with gnuradio 3.8 check out my fork: https://github.com/antoniprzybylik/multi-rtl

Thanks for reply i have fix this issue , but how  i can know that the multi-rtl device is working fine , i cant know!
i have tried many times to do it with my hand but its not working , is there any website selling it hand made ? or you dan help me with it ? i can pay!
